### ISSUE TITLE
Structural changes of FortnoxWebSocketClient

### ISSUE THREAD

**Issue by brokenprogrammer** [zenta-ab/fortnox.NET#19]
During development of the [FortnoxWebSocketClient ](https://github.com/zenta-ab/fortnox.NET/blob/master/Fortnox.NET/WebSockets/FortnoxWebSocketClient.cs) it was somewhere along the way decided to be implemented as a fluent interface through method chaining. 

Example: 
```CSharp
var client = new FortnoxWebSocketClient(this.connectionSettings.AccessToken, this.connectionSettings.ClientSecret)
    .AddTopic(WebSocketTopic.Articles)
    .AddTopic(WebSocketTopic.Orders)
    .Connect();
```

This internally was developed by putting everything within the [Connect](https://github.com/zenta-ab/fortnox.NET/blob/master/Fortnox.NET/WebSockets/FortnoxWebSocketClient.cs#L128) method meaning the [AddTopic](https://github.com/zenta-ab/fortnox.NET/blob/master/Fortnox.NET/WebSockets/FortnoxWebSocketClient.cs#L174) were only keeping track of which Topics to subscribe to once subscribing to the Fortnox WebSocket. This is a faulty implementation since users may want to subscribe to Topcis "on the fly" while keeping their WebSocket alive. The same goes for adding additional tenants.

My suggestion is not to scrap the fluent interface but instead bringing back AddTopic, AddTenant and Subscribe as their own methods as an action instead of what they are now in their current implementation. Allowing the users to AddTenants, or Topics whenever they want. However a fluent api in this sense doesn't make much sense to me due to everything being asynchronous operations hence using a "creational" type of builder pattern for websockets seems weird and the fluent api becomes less fluent when `await (await client.Connect()).Listen(...);` is the code you end up writing.

Instead we might be looking at an interface like this:
```CSharp
var client = new FortnoxWebSocketClient(this.connectionSettings.AccessToken, this.connectionSettings.ClientSecret);

// Do some stuff..
await client.Subscribe();

// Do some more stuff..
await client.AddTopic(WebSocketTopic.Orders);

// Do even more stuff..
await client.AddTenant(TenantAccessToken);
``` 

In my opinion one thing is missing here and that is keeping track of the responses when adding for example a new Tenant. If we provide an invalid AccessToken we might want to handle that response somehow and sure this could be implemented like:
`var addTenantResponse = await client.AddTenant(InvalidAccessToken);` 

But due to the underlying [ClientWebSocket](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netcore-3.1) implementation which the FortnoxWebSocketClient is based upon we arrive at a problem where only one `Send` and one `Recieve` is supported on each ClientWebSocket object in parallel.

My thoughts about solving this is to actually make an implementation for the `Listen` method in FortnoxWebSocketClient which instead of a callback for what to do with the underlying socket accepts a callback with the response whatever the response is, either an event or a command response such as the response expected when adding tenants, this allows the user to implement their own error handling as well.

As for how this is implemented we already have a `GetNextEvent` which in a sense already does this but unfortunately only handles WebSocketEvent objets. 

This can be solved with a superclass which all the different message types inherit from or we can experiment with Delegates or covariance / contravariance.

Note that this type of change would introduce breaking changes in the current WebSocket API but its better to fix theese type of things now instead of trying to patch an already existing code smell.

### Resources:
[Using Delegates (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/using-delegates)
[Using Variance for Func and Action Generic Delegates (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/using-variance-for-func-and-action-generic-delegates)
[Creating Variant Generic Interfaces (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces)

**Comment by GGAlanSmithee** [comment]
Good writeup @brokenprogrammer 

My overall feedback is that we need to clearly state the high level goals of the webhook API and then derive the implementation from that.

From what I gather we want an API that let you

1. Establish one (or more?) websocket connection(s)
2. Add (and remove?) tenants, subscriptions and topics on the fly
3. Receive / send messages per subscription / topic
4. More?

Seems to me like you have a pretty good understanding of the needed / wanted functionality and proposed solution. I cannot speak to that since I don't fully understand the details of it, but I can offer some thoughts / questions :)

What is a tenant in the context of a Fortnox Webhook connection - a Fortnox tenant I would assume? Would that be for usage within a SaaS application etc? If so, how does that relate to topics and subscriptions - are they per tenant and if so how can we differentiate between them in that situation? Should we, or is that for the end user to do, and if so how can we bake that into the super class you describe?

Also, to continue the above train of thoughts, what is the idea behind having to instatiate a `FortnoxWebSocketClient`?  Do we support the usecase of multiple clients in one application, and if so what are the implications of that in regards to situations like having multiple clients subscribing to the same topics etc?

I do like the general direction of you proposed changes and also the modification to `GetNextEvent` with a shared base class. Regarding the API being fluent or not, I don't have a strong opinion except that we should follow sound API design in regards to usability and guessability and follow the path of least resistance.

Also, like to point out that this is a breaking change AKA a major version bump, so we shouldn't necessarily let big changes scare us, even though we want to make migrating as easy as possible.

Got any thoughts on this @BaconFinger?

**Comment by GGAlanSmithee** [comment]
Also, @brokenprogrammer can you please clarify the below:

> But due to the underlying ClientWebSocket implementation which the FortnoxWebSocketClient is based upon we arrive at a problem where only one Send and one Recieve is supported on each ClientWebSocket object in parallel.

I know we talked about it, but please refresh my memory

**Comment by brokenprogrammer** [comment]
> From what I gather we want an API that let you
> 1. Establish one (or more?) websocket connection(s)

This is already possible.

> 2. Add (and remove?) tenants, subscriptions and topics on the fly

Yes, this is not supported in the current implementation and is the main reason for this issue.

> 3. Receive / send messages per subscription / topic

I think we do not have to provide too much detail when it comes to how users should deal with their events. So mainly the API should let you Send and Recieve messages. Perhaps we simply implement it just like that instead of any fancy listen implementation with delegates since that allows for the most freedom anyway.

> 4. More?

Not really.

> What is a tenant in the context of a Fortnox Webhook connection - a Fortnox tenant I would assume? 

Correct. Its one users fortnox account which we can listen to events on.

> Would that be for usage within a SaaS application etc?

I do not fully understand this question but its a vital part of being able to use their websocket API as intended. Maybe you have a running WebSocket that is listening to events and during its lifetime you want to add additional tenants to listen to. A topic is a single topic, for example "Orders" or "Articles" updating or creating a new order would trigger an event with the order topic. They are related to whichever tenant owns the order. We differentiate between them via a tenantID which is given back to us when we add tenants.

> Should we, or is that for the end user to do, and if so how can we bake that into the super class you describe?

We should allow for the user to somehow keep track of which tenant is which. This can easily be done through a dictionary for example.

> Also, to continue the above train of thoughts, what is the idea behind having to instatiate a FortnoxWebSocketClient? Do we 
> support the usecase of multiple clients in one application, and if so what are the implications of that in regards to situations 
> like having multiple clients subscribing to the same topics etc?

There is nothing preventing a user from having one instance of FortnoxWebSocketClient per tenant. But also probably nothing preventing the user from ading the same tenant to multiple clients.. In my oppinion this wrapper makes sense but please clarify how it wouldn't.

> Also, @brokenprogrammer can you please clarify the below: ..

It can be found here under "Remarks": [https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket.receiveasync?view=netcore-3.1#System_Net_WebSockets_ClientWebSocket_ReceiveAsync_System_ArraySegment_System_Byte__System_Threading_CancellationToken_](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket.receiveasync?view=netcore-3.1#System_Net_WebSockets_ClientWebSocket_ReceiveAsync_System_ArraySegment_System_Byte__System_Threading_CancellationToken_)

What I meant was that If the user would register a listener just lying there recieveing events then the call like
`var addTenantResponse = await client.AddTenant(InvalidAccessToken);`
wouldn't work because to get the `addTenantResponse` we would have to recieve after we send the command to add a new tenant which would throw.

**Comment by GGAlanSmithee** [comment]
Ok, great!

As per our in-person conversation, we create a bare bones implementation of `Listen` and `Receive` with support of pt 2 above. Also, we let the tenant-subscription/topic mapping be handled in userspace since it's probably on a per usecase basis on how that should be handled.

Let's add documentation regarding the rational behind the tenant aspect - that we don't handle it specifically, but that we expose the needed information as received by Fortnox.

**Comment by brokenprogrammer** [comment]
This has been adressed with PR #20. 

Closing.
